name: Humm-salesforce-sonar-check

on:
  push:
    branches: [ master ]

jobs:
  sonarcloud:
    name: SonarCloud checks
    runs-on: ubuntu-latest
    steps:
      - uses: mktcode/consecutive-workflow-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm install --save --legacy-peer-deps
      - name: Run test
        run: npm test
      - name: Sonar properties configuration
        run: |
            touch sonar-project.properties
            echo sonar.projectKey=${{ secrets.SONARPROJECTKEY }} >> sonar-project.properties
            echo sonar.organization=${{ secrets.SONARORG }} >> sonar-project.properties
            echo sonar.exclusions=${{ secrets.EXCLUSIONS }} >> sonar-project.properties
            echo sonar.javascript.lcov.reportPaths=${{ secrets.SONARCOV }} >> sonar-project.properties 
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: '${{ secrets.ACCESS_TOKEN }}'
          SONAR_TOKEN: '${{ secrets.SONAR_TOKEN }}'
      - name: Sonarcloud Quality Gate check
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
